### ISSUE TITLE
Alterar a tela do GIF (Browser)

### ISSUE THREAD

**Issue by fernanDOTdo** [codigofalado/twitch-giphy#4]
Alterar a tela do GIF (Browser) para exibir o Username + Balão estilo quadrinhos que cerca todo o GIF.

Exemplo: 
![Balao](https://upload.wikimedia.org/wikipedia/commons/3/37/Speech_balloon.svg)

**Comment by alexandreramosdev** [comment]
Quero começar a fazer está feature! Mas não compreendir muito bem como seria meu start de desenvolvimento! Ja preenchi todos os dados do .env !  O proximo passo seria abrir uma live? para ir testando?
